Use distinct logger services

diff --git a/freebsd10/usr/local/sbin/cloudpasswd b/freebsd10/usr/local/sbin/cloudpasswd
--- a/freebsd10/usr/local/sbin/cloudpasswd
+++ b/freebsd10/usr/local/sbin/cloudpasswd
@@ -1,6 +1,10 @@
 #!/bin/sh
 #
-# FreeBSD
+# Init file for Password Reset Client for FreeBSD
+#
+# chkconfig: 345 98 02
+# description: Password Reset Client
+
 # Modify this line to specify the user (default is root)
 user=root
 
@@ -16,9 +20,7 @@ password_received=0
 file_count=0
 error_count=0
 
-${LOG} -t "cloud" "cloud-set-guest-password was called"
 for DHCP_FILE in $DHCP_FILES; do
-  ${LOG} -t "cloud" "DHCP_FILE: $DHCP_FILE"
   if [ -f $DHCP_FILE ]; then
     file_count=$((file_count+1))
     maxcheck=15
@@ -27,53 +29,53 @@ for DHCP_FILE in $DHCP_FILES; do
     until valip ${ip}; do
       [ $ipcheck -eq $maxcheck ] && continue 2
       sleep 3
-      ${LOG} -t "cloud" "No valid IP \"${ip}\" found in ${DHCP_FILE}"
+      ${LOG} -t "cloud-passwd" "No valid IP \"${ip}\" found in ${DHCP_FILE}"
       ip="$(awk -F ' |;' '/dhcp-server-identifier/ { print $5 }' ${DHCP_FILE} | tail -1)"
       ipcheck=$((ipcheck+1))
     done
     PASSWORD_SERVER_IP=$ip
     if [ -n $PASSWORD_SERVER_IP ]; then
-      ${LOG} -t "cloud" "Found password server IP \"${PASSWORD_SERVER_IP}\" in \"${DHCP_FILE}\""
-      ${LOG} -t "cloud" "Sending request to password server at \"${PASSWORD_SERVER_IP}\""
+      ${LOG} -t "cloud-passwd" "Found password server IP \"${PASSWORD_SERVER_IP}\" in \"${DHCP_FILE}\""
+      ${LOG} -t "cloud-passwd" "Sending request to password server at \"${PASSWORD_SERVER_IP}\""
       password=$(${WGET} -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
       passcheck=0
       until [ $? -ne 4 ]; do
         [ $passcheck -eq $maxcheck ] && continue 2
         sleep 3
-        ${LOG} -t "cloud" "Wget exited with exit code $?, retrying"
+        ${LOG} -t "cloud-passwd" "Wget exited with exit code $?, retrying"
         password=$(${WGET} -q -t 3 -T 20 -O - --header "DomU_Request: send_my_password" $PASSWORD_SERVER_IP:8080)
         passcheck=$((passcheck+1))
       done
       password=$(echo $password | tr -d '\r')
 
       if [ $? -eq 0 ]; then
-        ${LOG} -t "cloud" "Got response from server at $PASSWORD_SERVER_IP"
+        ${LOG} -t "cloud-passwd" "Got response from server at $PASSWORD_SERVER_IP"
         case $password in
           "")
-            ${LOG} -t "cloud" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
+            ${LOG} -t "cloud-passwd" "Password server at $PASSWORD_SERVER_IP did not have any password for the VM"
             continue
             ;;
           "bad_request")
-            ${LOG} -t "cloud" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
+            ${LOG} -t "cloud-passwd" "VM sent an invalid request to password server at $PASSWORD_SERVER_IP"
             error_count=$((error_count+1))
             continue
             ;;
           "saved_password")
-            ${LOG} -t "cloud" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
+            ${LOG} -t "cloud-passwd" "VM has already saved a password from the password server at $PASSWORD_SERVER_IP"
             continue
             ;;
           *)
-            ${LOG} -t "cloud" "VM got a valid password from server at $PASSWORD_SERVER_IP"
+            ${LOG} -t "cloud-passwd" "VM got a valid password from server at $PASSWORD_SERVER_IP"
             password_received=1
             break
             ;;
         esac
       else
-        ${LOG} -t "cloud" "Failed to send request to password server at $PASSWORD_SERVER_IP"
+        ${LOG} -t "cloud-passwd" "Failed to send request to password server at $PASSWORD_SERVER_IP"
         error_count=$((error_count+1))
       fi
     else
-      ${LOG} -t "cloud" "Could not find password server IP in $DHCP_FILE"
+      ${LOG} -t "cloud-passwd" "Could not find password server IP in $DHCP_FILE"
       error_count=$((error_count+1))
     fi
   fi
@@ -81,30 +83,30 @@ done
 
 if [ "$password_received" == "0" ]; then
   if [ "$error_count" == "$file_count" ]; then
-    ${LOG} -t "cloud" "Failed to get password from any server"
+    ${LOG} -t "cloud-passwd" "Failed to get password from any server"
     exit 1
   else
-    ${LOG} -t "cloud" "Did not need to change password."
+    ${LOG} -t "cloud-passwd" "Did not need to change password."
     exit 0
   fi
 fi
 
-${LOG} -t "cloud" "Changing password ..."
+${LOG} -t "cloud-passwd" "Changing password ..."
 echo $password | pw mod user $user -h 0
 
 if [ $? -gt 0 ]; then
   echo "${password}" | /usr/sbin/pw usermod -u 0 -h 0 2>/dev/null
   if [ $? -gt 0 ]; then
-    ${LOG} -t "cloud" "Failed to change password for user $user"
+    ${LOG} -t "cloud-passwd" "Failed to change password for user $user"
     exit 1
   fi
 else
-  ${LOG} -t "cloud" "Successfully changed password for user $user"
+  ${LOG} -t "cloud-passwd" "Successfully changed password for user $user"
 fi
 
 # Plesk password change if the /etc/psa folder is an existing directory
 [ -d /etc/psa/ ] && PSA_PASSWORD=$password /usr/local/psa/admin/bin/ch_admin_passwd > /dev/null 2>&1
 
-${LOG} -t "cloud" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
+${LOG} -t "cloud-passwd" "Sending acknowledgment to password server at $PASSWORD_SERVER_IP"
 ${WGET} -t 3 -T 20 -q -O /dev/null --header "DomU_Request: saved_password" $PASSWORD_SERVER_IP:8080
 exit 0
diff --git a/freebsd10/usr/local/sbin/cloudsshkey b/freebsd10/usr/local/sbin/cloudsshkey
--- a/freebsd10/usr/local/sbin/cloudsshkey
+++ b/freebsd10/usr/local/sbin/cloudsshkey
@@ -20,9 +20,7 @@ keys_received=0
 file_count=0
 error_count=0
 
-${LOG} -t "cloud" "cloud-set-guest-sshkey was called"
 for DHCP_FILE in $DHCP_FILES; do
-  ${LOG} -t "cloud" "DHCP_FILE: $DHCP_FILE"
   if [ -f $DHCP_FILE ]; then
     file_count=$((file_count+1))
     maxcheck=15
@@ -31,47 +29,48 @@ for DHCP_FILE in $DHCP_FILES; do
     until valip ${ip}; do
       [ $ipcheck -eq $maxcheck ] && continue 2
       sleep 3
-      ${LOG} -t "cloud" "No valid IP \"${ip}\" found in ${DHCP_FILE}"
+      ${LOG} -t "cloud-sshkey" "No valid IP \"${ip}\" found in ${DHCP_FILE}"
       ip="$(awk -F ' |;' '/dhcp-server-identifier/ { print $5 }' ${DHCP_FILE} | tail -1)"
       ipcheck=$((ipcheck+1))
     done
     SSHKEY_SERVER_IP=$ip
     if [ -n $SSHKEY_SERVER_IP ]; then
-      ${LOG} -t "cloud" "Found ssh key server server IP \"${PASSWORD_SERVER_IP}\" in \"${DHCP_FILE}\""
-      ${LOG} -t "cloud" "Sending request to ssh key server at \"${SSHKEY_SERVER_IP}\""
+      ${LOG} -t "cloud-sshkey" "Found ssh key server IP \"${SSHKEY_SERVER_IP}\" in \"${DHCP_FILE}\""
+      ${LOG} -t "cloud-sshkey" "Sending request to ssh key server at \"${SSHKEY_SERVER_IP}\""
       publickey=$($WGET -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)
       sshkeycheck=0
       until [ $? -ne 4 ]; do
-        [ $passcheck -eq $maxcheck ] && continue 2
+        [ $sshkeycheck -eq $maxcheck ] && continue 2
         sleep 3
-        ${LOG} -t "cloud" "Wget exited with exit code $?, retrying"
+        ${LOG} -t "cloud-sshkey" "Wget exited with exit code $?, retrying"
         publickey=$(${WGET} -q -t 3 -T 20 -O - http://$SSHKEY_SERVER_IP/latest/public-keys 2>/dev/null)
         sshkeycheck=$((sshkeycheck+1))
       done
       sshkey=$(echo $sshkey | tr -d '\r')
 
       if [ $? -eq 0 ]; then
-        ${LOG} -t "cloud" "Got response from server at $SSHKEY_SERVER_IP"
+        ${LOG} -t "cloud-sshkey" "Got response from server at $SSHKEY_SERVER_IP"
         keys_received=1
         break
       fi
     else
-      ${LOG} -t "cloud" "Could not find ssh key server IP in $DHCP_FILE"
+      ${LOG} -t "cloud-sshkey" "Could not find ssh key server IP in $DHCP_FILE"
     fi
   fi
 done
 
 if [ "$keys_received" == "0" ]; then
   if [ "$error_count" == "$file_count" ]; then
-    ${LOG} -t "cloud" "Failed to get ssh keys from any server"
+    ${LOG} -t "cloud-sshkey" "Failed to get ssh keys from any server"
     exit 1
   else
-    ${LOG} -t "cloud" "Did not need to set ssh keys."
+    ${LOG} -t "cloud-sshkey" "Did not need to set ssh keys."
     exit 0
   fi
 fi
 
 # set ssh public key
+${LOG} -t "cloud-sshkey" "Adding ssh public key ..."
 homedir=$(grep ^$user /etc/passwd|awk -F ":" '{print $6}')
 sshdir=$homedir/.ssh
 authorized=$sshdir/authorized_keys
